install:
    game-settings:
        accountId: 2944490259
        modified: false
        timestamp: 1556683749459
    gameflow-patcher-lock: null
    gameflow-process-info: null
    gameflow-spectate-reconnect-info: null
    globals:
        locale: "zh_CN"
        region: "TENCENT"
    last-valid-login-splash:
        theme: "season2018-post"
        version: "1.50"
    lcu-settings:
        accountId: 2944490259
        modified: false
        timestamp: 1556677670774
    npe-splash:
        enableNewPlayerSplash: false
    patcher:
        client_migrated: false
        client_patcher_available: false
        game_migrated: false
        game_patcher_available: false
    perks-settings:
        accountId: 2944490259
        modified: false
        timestamp: 1556682274422
    rso-auth:
        install-identifier: "95d958b40207254197bdaa702779ee4d"
    telemetry:
        fresh_installation: true
        installation_id: "C402Dg=="
